args <- commandArgs(trailingOnly = FALSE)
file_arg <- grep("^--file=", args, value = TRUE)
if (length(file_arg) > 0) {
  script_path <- normalizePath(sub("^--file=", "", file_arg[1]), mustWork = TRUE)
  article_root <- normalizePath(file.path(dirname(script_path), ".."), mustWork = TRUE)
} else {
  article_root <- getwd()
}
setwd(article_root)
tables_dir <- file.path(article_root, "outputs", "tables")
figures_dir <- file.path(article_root, "outputs", "figures")
dir.create(tables_dir, recursive = TRUE, showWarnings = FALSE)
dir.create(figures_dir, recursive = TRUE, showWarnings = FALSE)
records <- read.csv(file.path(article_root, "data", "narrative_formula_drift_claims.csv"), stringsAsFactors = FALSE)
records$formula_drift <- pmin(1, records$template_forcing * 0.20 + records$beat_rigidity * 0.18 + records$closure_pressure * 0.18 + records$universality_pressure * 0.16 + records$automation_dependence * 0.14 + (1 - records$story_specificity) * 0.14)
records$framework_health <- rowMeans(records[, c("scope_clarity", "context_sensitivity", "alternative_lenses", "refusal_monitoring", "ethical_governance", "human_judgment")])
records$narrative_specificity <- rowMeans(records[, c("voice_originality", "place_logic", "temporal_method", "material_detail", "relational_logic", "cultural_specificity")])
records$ai_template_risk <- pmin(1, records$default_arc_use * 0.18 + records$generic_phrasing * 0.18 + records$heroic_arc_pressure * 0.18 + records$market_story_pressure * 0.16 + records$resolution_smoothing * 0.16 + (1 - records$variant_comparison) * 0.14)
records$governance_priority_score <- pmin(1, records$formula_drift * 0.32 + records$ai_template_risk * 0.24 + (1 - records$framework_health) * 0.16 + (1 - records$narrative_specificity) * 0.12 + records$public_consequence * 0.16)
records$review_priority <- ifelse(records$status == "revise" | records$governance_priority_score >= 0.62, "high", ifelse(records$status == "review" | records$governance_priority_score >= 0.45, "medium", "standard"))
records <- records[order(records$governance_priority_score, decreasing = TRUE), ]
write.csv(records, file.path(tables_dir, "narrative_formula_drift_diagnostics.csv"), row.names = FALSE)
write.csv(records[records$review_priority != "standard", ], file.path(tables_dir, "narrative_formula_drift_governance_queue.csv"), row.names = FALSE)
png(file.path(figures_dir, "formula_drift_scores.png"), width = 1200, height = 700)
barplot(records$formula_drift, names.arg = records$item, las = 2, ylab = "Formula drift", main = "Narrative Formula Drift")
grid()
dev.off()
print(records[, c("item", "formula_drift", "framework_health", "narrative_specificity", "ai_template_risk", "review_priority")])
