# Base R workflow for Narrative Identity and the Story of the Self.
args <- commandArgs(trailingOnly = FALSE)
file_arg <- grep("^--file=", args, value = TRUE)
if (length(file_arg) > 0) {
  script_path <- normalizePath(sub("^--file=", "", file_arg[1]), mustWork = TRUE)
  article_root <- normalizePath(file.path(dirname(script_path), ".."), mustWork = TRUE)
} else { article_root <- getwd() }
setwd(article_root)
tables_dir <- file.path(article_root, "outputs", "tables")
figures_dir <- file.path(article_root, "outputs", "figures")
dir.create(tables_dir, recursive = TRUE, showWarnings = FALSE)
dir.create(figures_dir, recursive = TRUE, showWarnings = FALSE)
records <- read.csv(file.path(article_root, "data", "narrative_identity_claims.csv"), stringsAsFactors = FALSE)
records$narrative_coherence <- rowMeans(records[, c("memory_continuity", "temporal_progression", "agency", "relational_grounding", "promise_responsibility", "future_openness")])
records$revision_readiness <- rowMeans(records[, c("change_handling", "memory_revision", "uncertainty_notes", "counter_memory", "silence_respect", "openness_to_retelling")])
records$identity_story_risk <- pmin(1, records$reduction_risk * 0.18 + records$forced_coherence * 0.20 + records$power_blindness * 0.18 + records$trauma_extraction * 0.18 + records$algorithmic_capture * 0.16 + (1 - records$cultural_context) * 0.10)
records$interpretation_readiness <- rowMeans(records[, c("source_context", "cultural_context", "method_limits", "uncertainty_notes", "ethics_governance", "review_owner_clarity")])
records$governance_priority_score <- pmin(1, records$identity_story_risk * 0.40 + (1 - records$interpretation_readiness) * 0.28 + records$public_consequence * 0.16 + (1 - records$revision_readiness) * 0.16)
records$review_priority <- ifelse(records$status == "revise" | records$governance_priority_score >= 0.62, "high", ifelse(records$status == "review" | records$governance_priority_score >= 0.45, "medium", "standard"))
records <- records[order(records$governance_priority_score, decreasing = TRUE), ]
write.csv(records, file.path(tables_dir, "narrative_identity_diagnostics.csv"), row.names = FALSE)
write.csv(records[records$review_priority != "standard", ], file.path(tables_dir, "narrative_identity_governance_queue.csv"), row.names = FALSE)
png(file.path(figures_dir, "narrative_coherence_scores.png"), width = 1200, height = 700)
barplot(records$narrative_coherence, names.arg = records$item, las = 2, ylab = "Narrative coherence", main = "Narrative Identity Coherence")
grid(); dev.off()
png(file.path(figures_dir, "identity_story_risk_scores.png"), width = 1200, height = 700)
barplot(records$identity_story_risk, names.arg = records$item, las = 2, ylab = "Identity-story risk", main = "Narrative Identity Ethical Risk")
grid(); dev.off()
print(records[, c("item", "claim_context", "narrative_coherence", "revision_readiness", "identity_story_risk", "interpretation_readiness", "review_priority")])
